driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-7.1
suites:
- name: default
  run_list:
  - recipe[snort]
  - recipe[pulledpork]
  attributes:
    pulledpork:
      rule_url_array:
        - 'https://s3.amazonaws.com/snort-org/www/rules/community/|community-rules.tar.gz|Community'
